// <auto-generated />
using DemoAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260119215206_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoAPI.Models.Shirt", b =>
                {
                    b.Property<int>("ShirtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShirtId"));

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("ShirtId");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            ShirtId = 1,
                            BrandName = "Country Road",
                            Colour = "Red",
                            Gender = "men",
                            Price = 199,
                            Size = 34
                        },
                        new
                        {
                            ShirtId = 2,
                            BrandName = "Zara",
                            Colour = "Blue",
                            Gender = "women",
                            Price = 249,
                            Size = 28
                        },
                        new
                        {
                            ShirtId = 3,
                            BrandName = "Woolworths",
                            Colour = "Green",
                            Gender = "men",
                            Price = 149,
                            Size = 30
                        },
                        new
                        {
                            ShirtId = 4,
                            BrandName = "Polo",
                            Colour = "Black",
                            Gender = "women",
                            Price = 299,
                            Size = 32
                        },
                        new
                        {
                            ShirtId = 5,
                            BrandName = "Levis",
                            Colour = "White",
                            Gender = "men",
                            Price = 176,
                            Size = 36
                        },
                        new
                        {
                            ShirtId = 6,
                            BrandName = "Guess",
                            Colour = "Yellow",
                            Gender = "men",
                            Price = 219,
                            Size = 26
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
