using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using static System.Net.Mime.MediaTypeNames;

using System;
using Microsoft.IdentityModel.JsonWebTokens;

namespace DemoAPI.Authority
{
    public static class Authenticator
    {
        public static bool Authenticate(string clientId, string secret)
        {
            var app = AppRepository.GetApplicationByClientId(clientId);
            if (app == null) return false;
            
            return (app.ClientId == clientId && app.Secret == secret);
        }


        public static string CreateToken(string clientId, DateTime expiresAt, string secretKey)
        {
            // The JWT Strucure consists of three parts: Header, Payload, and Signature (Signing key)

            //Algorithm
            var signingCredentials = new SigningCredentials(
                new SymmetricSecurityKey(System.Text.Encoding.UTF8.GetBytes(secretKey)),
                SecurityAlgorithms.HmacSha256Signature);

            //Payload Claims
            var app = AppRepository.GetApplicationByClientId(clientId);
            var claimsDictionary = new Dictionary<string, object>
            {
                {"AppName", app?.ApplicationName ?? string.Empty }
            };

            // Extract claims
            var scopes = app?.Scopes?.Split(',') ?? Array.Empty<string>();

            if(scopes.Length > 0)
            {
                foreach(var scope in scopes)
                {
                    claimsDictionary.Add(scope.Trim().ToLower(),  "true");
                }
            }

            var tokenDescriptor = new SecurityTokenDescriptor
            {
                SigningCredentials = signingCredentials,
                Claims = claimsDictionary,
                Expires = expiresAt,
                NotBefore = DateTime.UtcNow
            };


            var tokenHandler = new JsonWebTokenHandler();

            //Signature is automatically generated by the token handler when we create the token using the signing credentials and the payload claims.
            return tokenHandler.CreateToken(tokenDescriptor);
        }

        public static async Task<IEnumerable<Claim>?> VerifyTokenAsync(string tokenString, string securityKey)
        {
            if (string.IsNullOrWhiteSpace(tokenString) || string.IsNullOrWhiteSpace(securityKey))
            {
                return null; 
            }

            var keyBytes = System.Text.Encoding.UTF8.GetBytes(securityKey); // Convert the security key string to bytes
            var tokenHandler = new JsonWebTokenHandler(); // Create an instance of the token handler

            var validationParameters = new TokenValidationParameters
            {
                ValidateIssuerSigningKey = true, // Ensure the signing key is valid
                IssuerSigningKey = new SymmetricSecurityKey(keyBytes), // Use the provided security key for validation
                ValidateIssuer = false, // Adjust as needed
                ValidateAudience = false, // Adjust as needed
                ValidateLifetime = true, // Ensure the token hasn't expired
                ClockSkew = TimeSpan.Zero // Optional: Set clock skew to zero for strict expiration validation
            };

            try
            {
                var result = await tokenHandler.ValidateTokenAsync(tokenString, validationParameters);
                
                if(result.SecurityToken != null)
                {
                    var tokenObject = tokenHandler.ReadJsonWebToken(tokenString);
                    return tokenObject.Claims ?? Enumerable.Empty<Claim>();
                }
                else
                {
                    //Token is not valid
                    return null;
                }
            }
            catch (SecurityTokenMalformedException)
            {
                return null; // Token is malformed
            }
            catch (SecurityTokenExpiredException)
            {
                return null; //Token has expired
            }
            catch (SecurityTokenInvalidSignatureException)
            {
                return null; // Signature validation failed
            }
            catch (Exception)
            {
                throw; // Rethrow any other unexpected exceptions
            }
        }
    }
}
