using Microsoft.IdentityModel.JsonWebTokens;
using Microsoft.IdentityModel.Tokens;
using static System.Net.Mime.MediaTypeNames;

namespace DemoAPI.Authority
{
    public static class Authenticator
    {
        public static bool Authenticate(string clientId, string secret)
        {
            var app = AppRepository.GetApplicationByClientId(clientId);
            if (app == null) return false;
            
            return (app.ClientId == clientId && app.Secret == secret);
        }


        public static string CreateToken(string clientId, DateTime expiresAt, string secretKey)
        {
            // The JWT Strucure consists of three parts: Header, Payload, and Signature (Signing key)

            //Algorithm
            var signingCredentials = new SigningCredentials(
                new SymmetricSecurityKey(System.Text.Encoding.UTF8.GetBytes(secretKey)),
                SecurityAlgorithms.HmacSha256Signature);

            //Payload
            var app = AppRepository.GetApplicationByClientId(clientId);
            var claimsDictionary = new Dictionary<string, object>
            {
                {"AppName", app?.ApplicationName?? string.Empty },
                {"Read", (app?.Scopes ?? string.Empty).Contains("read")? "true" : "false" },
                {"Write", (app?.Scopes ?? string.Empty).Contains("write")? "true" : "false" },
                {"Delete", (app?.Scopes ?? string.Empty).Contains("delete")? "true" : "false" }
            };


            var tokenDescriptor = new SecurityTokenDescriptor
            {
                SigningCredentials = signingCredentials,
                Claims = claimsDictionary,
                Expires = expiresAt,
                NotBefore = DateTime.UtcNow
            };


            var tokenHandler = new JsonWebTokenHandler();

            //Signature is automatically generated by the token handler when we create the token using the signing credentials and the payload claims.
            return tokenHandler.CreateToken(tokenDescriptor);
        }
    }
}
